export interface CssVars {
  [token: string]: string;
}

export interface DecodedPreset {
  style: string;
  baseColor: string;
  theme: string;
  chartColor: string;
  font: string;
  fontHeading: string;
  iconLibrary: string;
  radius: string;
  menuAccent: string;
  menuColor: string;
}

export interface PresetData {
  /** Short preset code from the URL (`?preset=...`). */
  code?: string;
  /** Source URL the data came from. */
  sourceUrl?: string;
  /** ISO timestamp generated by the extractor. */
  generatedAt?: string;

  // Configuration
  style?: string;
  baseColor?: string;
  font?: string;
  iconLibrary?: string;
  radius?: string;

  // Full decoded preset (every field from the base62 bitpack).
  decoded?: DecodedPreset;

  // CSS variables
  cssVarsLight?: CssVars;
  cssVarsDark?: CssVars;
}
